### PR TITLE
AORC Forcings Basic Model Interfaces (ExactExtract Python, ExactExtract Manual Aerial Weighting Average)

### PR DESCRIPTION
**Pull request by jduckerOWP**
[Short description explaining the high-level reason for the pull request]

## Additions
AORC_BMI_EE_python directory (Basic Model Interface code for ExactExtract Python)
AORC_BMI_EE_manual_weights directory (Basic Model Interface code for ExactExtract Manual Aerial Weighting Average)
-

## Removals

-

## Changes
Implement AORC Basic Model Interface foundation that can be translated in the NextGen Framework. For any testing using the ExactExtract Python bindings, please see pull request "Regrid AORC using ExactExtract python bindings #8" in ngen-forcing repository for instructions to download and install ExactExtract python bindings. 
-

## Testing

1. Within each directory, go through the README.md file to understand the meaning behind each python script and instructions to test the AORC Basic Model Interface functionality. 

## Notes

-

## Todos

-

## Checklist

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows project standards (link if applicable)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Target Environment support

- [ ] Linux

### CODE REVIEW

**Comment by hellkite500** [comment]
I think we are going to have to merge the verbatim so we have a landing spot for the work which can be used/refined from there.  Please let me know if you have any small additions you want to get added, and we will look to merge this and update any documentation as needed over the next couple weeks.

**Comment by jduckerOWP** [comment]
@hellkite500 I was planning getting all of my latest work finally pushed up to my GitHub repo in the coming days. When would like a hard cut off line for merging my repo? This Friday or next Monday?

**Comment by hellkite500** [comment]
Let's get everything pushed by Friday, we can merge and see where we are at from there.

**Comment by jduckerOWP** [comment]
@hellkite500 everything has been pushed and updated to the repository. @program-- let me know if you have questions during your review of the repository. All upgrades are constrained of course just to the BMI directory in the repository, along with restructuring of files within the repository itself.

**Review by hellkite500 — APPROVED** [review]
Approving verbatim.  Functionality has been tested in various way ad-hoc, and this needs to get merged as the foundation for future development/use.

**Pull request merged**
